apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-clean-architecture-translate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-clean-architecture-translate
  template:
    metadata:
      labels:
        app: go-clean-architecture-translate
    spec:
      containers:
        - name: go-clean-architecture-translate
          image: 01092002/go-clean-architecture-translate:1.0.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: go-clean-architecture-translate-configmap
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-clean-architecture-translate-service
spec:
  type: NodePort
  selector:
    app: go-clean-architecture-translate
  ports:
    - name: http
      port: 9090
      targetPort: 8080