version: "3.9"

services:
  app:
    container_name: go-clean-architecture-translate
    image: 01092002/go-clean-architecture-translate:1.0.0
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      MYSQL_DSN: ${MYSQL_DSN_PROD}
      MYSQL_USER: ${MYSQL_USER_PROD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_PROD}
      MYSQL_HOST: ${MYSQL_HOST_PROD}
      MYSQL_PORT: ${MYSQL_PORT_PROD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "8080:8080"
