version: "3.9"

services:
  mysql:
    container_name: go-clean-architecture-translate-mysql
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "./data.sql:/docker-entrypoint-initdb.d/data.sql"
    env_file:
      - .env